#!/bin/bash
# Define the path to the manage_my_process script


MANAGE_SCRIPT="./manage_my_process"

if [ "$#" -eq 0 ]
then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi


start_process() 
{
    if [ -e "/var/run/my_process.pid" ]; then
        echo "manage_my_process is already started."
    else
        $MANAGE_SCRIPT &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
}


stop_process() 
{
    if [ -e "/var/run/my_process.pid" ]; then
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm "/var/run/my_process.pid"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}


restart_process() 
{
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
