#!/usr/bin/env bash
# Bash script that displays to infinity and beyond indefinitely


terminate_process()
{
  echo "I am invincible!!!"
  exit 0
}


trap terminate_process SIGTERM

while true
do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
