#!/usr/bin/env bash
#  Bash script to create a made-up story


IFS=":"
while read -r username x uid gid info home shell
do
    group_name=$(getent group $gid | cut -d ":" -f1)
    command_shell=$(basename "$shell")
    password=$(grep -w "^$username" /etc/shadow | cut -d ":" -f2)
    user_info=$(finger $username | grep -m 1 Login | cut -d ":" -f3)

    echo "The user $username is part of the $group_name gang,"
	"lives in $home, and rides $command_shell."
    echo "USER ID's place is protected by the passcode $password,"
	"more info about the user here: $user_info"
    echo ""
done < /etc/passwd
