#!/usr/bin/env bash
# Bash script to display time for 12 hours and 59 minutes


hour=0

while [ $hour -lt 12 ]
do
    echo "hour: $hour"
    minute=1

    while [ $minute -lt 60 ]
do
        echo $minute
        let minute+=1
    done

    let hour+=1
done
