#!/usr/bin/env bash
# Bash script to display the content of the current dir


for file in *
do

    if [[ $file != .* ]]
then

        name_part=$(echo "$file" | cut -d'-' -f2-)
        

        echo "- $name_part"
    fi
done
